openapi: 3.0.3
info:
  title: Bunpeg API
  version: 1.0.0
  description: |
    A service that allows clients to upload media and perform FFmpeg operations via REST endpoints.
    Includes support for chained operations with a single task ID.

servers:
  - url: http://localhost:8000

paths:
  /upload:
    post:
      summary: Upload a media file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  fileId:
                    type: string

  /transcode:
    post:
      summary: Transcode a file to a different format
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                targetFormat:
                  type: string
      responses:
        '200':
          description: Transcoding started
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string

  /trim:
    post:
      summary: Trim a media file by start time and duration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
                start:
                  type: string
                  description: Start time (e.g., "00:00:05")
                duration:
                  type: string
                  description: Duration to keep (e.g., "10")
      responses:
        '200':
          description: Trimming started
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string

  /extract-audio:
    post:
      summary: Extract audio from a video file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileId:
                  type: string
      responses:
        '200':
          description: Audio extraction started
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string

  /chain:
    post:
      summary: Perform multiple FFmpeg operations in sequence on a file
      description: |
        Supports chaining of operations like trim, extract-audio, and transcode.
        Operations are applied in the order given. Uses the same task ID for all steps.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - fileId
                - operations
              properties:
                fileId:
                  type: string
                operations:
                  type: array
                  items:
                    oneOf:
                      - type: object
                        required: [type, start, duration]
                        properties:
                          type:
                            type: string
                            enum: [trim]
                          start:
                            type: string
                          duration:
                            type: string
                      - type: object
                        required: [type]
                        properties:
                          type:
                            type: string
                            enum: [extract-audio]
                      - type: object
                        required: [type, format]
                        properties:
                          type:
                            type: string
                            enum: [transcode]
                          format:
                            type: string
      responses:
        '200':
          description: Chained processing started
          content:
            application/json:
              schema:
                type: object
                properties:
                  taskId:
                    type: string

  /status/{taskId}:
    get:
      summary: Get the status of a task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [queued, processing, completed, failed]
                  outputPath:
                    type: string
                    nullable: true
                  error:
                    type: string
                    nullable: true

  /download/{fileId}:
    get:
      summary: Download the original file
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Original file download
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /output/{fileId}:
    get:
      summary: Download the processed file
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Output file download
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
